
###################
# @zZPiglet
###################

 
# 115
# 进入"115"并摇一摇
http-request ^https?:\/\/proapi\.115\.com\/ios\/user\/takespc\? script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/115/115.js
  
# 便利蜂
# 进入"便利蜂"，点击"签到赚礼金"
http-request ^https:\/\/h5\.bianlifeng\.com\/meepo\/taskCenter\/home\/v\d script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Blibee/Blibee.js
  
# 滴滴出行
# 进入"滴滴出行"，若弹出"首次写入滴滴出行Token 成功"           
# APP
http-request ^https:\/\/as\.xiaojukeji\.com\/ep\/as\/toggles\? script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi_new.js
# WeChat-MiniApp
http-request ^https:\/\/common\.diditaxi\.com\.cn\/webapp\/config\/sidebar\? script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi_new.js
 
# 海底捞
# 进入"海底捞"app，手动签到一次或点击"签到"
http-request ^https:\/\/superapp\.kiwa-tech\.com\/app\/coupon\/customerLevelShow script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Haidilao/HaidilaoUsebonus.js, requires-body=true
http-request ^https:\/\/activity-1\.m\.duiba\.com\.cn\/signactivity\/getSignInfo script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Haidilao/HaidilaoUsebonus.js
  
# 奈雪
# 进入"奈雪点单"小程序，若弹出"首次写入奈雪の茶Token 成功"           
http-request ^https:\/\/webapi\.qmai\.cn\/web\/cy\/v\d\/store\/template-scene script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Naixue/Naixue.js
  
# 掌门好老师
# 进入"掌门好老师"，点击左上方"签到"或"📅"日历图标
http-request ^https:\/\/teacherapi\.zmlearn\.com\/v1\/teacherApp\/app\/points\/taskCenter script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/ZMTeacher/ZMTeacher.js

# 小黑盒
# 进入"小黑盒"- "我"，若弹出"首次写入heybox Cookie 成功"即可         
http-request ^https:\/\/api\.xiaoheihe\.cn\/account\/home_v2\/\? script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/heybox/heybox.js
  
# 达美乐
# 进入微信公众号"达美乐比萨"- "优惠｜咨询" - "有奖游戏"，正常游戏一次并获取验证码         
http-request ^https?:\/\/dominos0724\.shjimang\.com\/Ajax\/GetSmsCode script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Domino/Domino_getSMS.js, requires-body=true
  
###################
# @toulanboy
###################

# 京东价格提醒
# 前往boxjs，填写你需要监控的京东链接和目标价格
http-request ^https:\/\/apapia-history\.manmanbuy\.com\/ChromeWidgetServices\/WidgetServices\.ashx script-path=https://raw.githubusercontent.com/toulanboy/scripts/master/jd_price_detect/jd_price_detect.js, requires-body=true

