
###################
# @zZPiglet
###################

# 115
# 进入"115"并摇一摇
cron "1 0 * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/115/115.js, tag=115

# 便利蜂
# 进入"便利蜂"，点击"签到赚礼金"
cron "1 0 * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Blibee/Blibee.js, tag=便利蜂

# 滴滴出行
# 进入"滴滴出行"，若弹出"首次写入滴滴出行 Token 成功"
cron "0 1,20,21 * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/DiDi/DiDi_new.js, tag=滴滴出行

# 海底捞
# 进入"海底捞"app，手动签到一次或点击"签到"
cron "1 0 * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Haidilao/Haidilao.js, tag=海底捞

# 奈雪
# 进入"奈雪点单"小程序，若弹出"首次写入奈雪の茶 Token 成功"
cron "1 0 * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Naixue/Naixue.js, tag=奈雪

# 掌门好老师
# 进入"掌门好老师"，点击左上方"签到"或"📅"日历图标
cron "1 0 * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/ZMTeacher/ZMTeacher.js, tag=掌门好老师

# 饿了么
# 打开 APP, 访问下`我的`>`签到领红包`(左上角)
cron "1 0 * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/elem/elemCheckIn.js, tag=饿了么-打卡领红包

# 小黑盒
# 进入"小黑盒" - "我"，若弹出"首次写入heybox Cookie 成功"即可
cron "0 * * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/heybox/heybox.js, tag=小黑盒

# 达美乐
# 进入微信公众号"达美乐比萨" - "优惠｜咨询" - "有奖游戏"，正常游戏一次并获取验证码
cron "0 0 * * *" script-path=https://raw.githubusercontent.com/zZPiglet/Task/master/Domino/Domino_getSMS.js, tag=达美乐


###################
# @toulanboy
###################

# 京东价格提醒
# 前往boxjs，填写你需要监控的京东链接和目标价格
cron "5 0 * * *" script-path=https://raw.githubusercontent.com/toulanboy/scripts/master/jd_price_detect/jd_price_detect.js, tag=京东价格提醒

